### ISSUE TITLE
Exception when trying to write directly to a buffer with a parent

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#60]
Example:
```
auto bufParent = Anvil::Buffer::create_nonsparse(
	dev,
	1'000ull, /* size */
	Anvil::QueueFamily::QUEUE_FAMILY_GRAPHICS_BIT,static_cast<VkSharingMode>(vk::SharingMode::eExclusive),
	static_cast<VkBufferUsageFlags>(vk::BufferUsageFlagBits::eUniformBuffer),
	Anvil::MemoryFeatureFlagBits::MEMORY_FEATURE_FLAG_MAPPABLE | Anvil::MemoryFeatureFlagBits::MEMORY_FEATURE_FLAG_HOST_CACHED,
	nullptr
);
std::array<uint8_t,100> data;
auto bufChild = Anvil::Buffer::create_nonsparse(
	bufParent,
	0ull, /* start offset */
	data.size() *sizeof(data.front())
);
bufParent->write(0ull,data.size() *sizeof(data.front()),data.data()); // Works
bufChild->get_memory_block(0u)->write(0ull,data.size() *sizeof(data.front()),data.data()); // Works
bufChild->write(0ull,data.size() *sizeof(data.front()),data.data()); // std::bad_weak_ptr exception
```
The problem is that the _m_device_ptr_ of the child-buffer is not being initialized, resulting in a _std::bad_weak_ptr_ exception whenever a method is called that needs it.

**Comment by DominikWitczakAMD** [comment]
I've just pushed a major update where the existing weak_ptr/shared_ptr-centered design has been significantly redesigned. Would you mind checking if the issue continues to repro with the new solution? Thanks.

**Comment by Silverlan** [comment]
Just tested it on the latest version and the issue still persists, _m_device_ptr_ is still NULL and it's throwing a "Access violation reading location 0x0000000000000000" exception now.

**Comment by DominikWitczakAMD** [comment]
Fixed internally; the fix will be included in the next week's update. Thanks for reporting.
